#!/usr/bin/env python3
"""Paladin spell specs cloned from the highest WotLK talent ranks."""

from sod_dbc import *  # noqa: F401,F403

SKILL_RETRIBUTION = 184
SKILL_PROTECTION = 267
SKILL_HOLY = 594

AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL = 71
AURA_ABILITY_PERIODIC_CRIT = 286
AURA_ADD_PCT_MODIFIER = 108
AURA_MOD_STUN = 12
PROC_DONE_MAGIC_POS = 0x00004000
PROC_DONE_PERIODIC = 0x00040000
PROC_HIT_CRITICAL = 0x00000002


def build(idx):
    """Return Paladin spells cloned from their level-80 WotLK ranks."""
    duration_5000 = idx["dur"][5000]
    icon_art_of_war = idx["icon"]["ability_paladin_artofwar"]
    icon_righteous_vengeance = idx["icon"]["ability_paladin_righteousvengeance"]
    cast_instant = idx["cast"][0]
    cast_2s = idx["cast"][2000]
    duration_permanent = idx["dur"][-1]
    duration_12s = idx["dur"][12000]
    duration_2s = idx["dur"][2000]
    range_self = idx["range"][0.0]
    icon_hammer_of_wrath = idx["icon"]["ability_thunderclap"]
    icon_holy_wrath = idx["icon"]["spell_holy_excorcism"]
    icon_fanaticism = idx["icon"]["spell_holy_greaterheal"]
    icon_wrath = idx["icon"]["ability_paladin_sanctifiedwrath"]

    return [
        {  # Divine Storm: the core script handles the party heal.
            "id": 407778, "client": True, "template": 53385,
            "skill_line": SKILL_RETRIBUTION,
            "name": "Divine Storm", "script": "spell_pal_divine_storm",
            "inherit_server": True,
            "overrides": {
                "SpellLevel": 0,
            },
        },
        {  # Avenger's Shield: remove the WotLK category cooldown.
            "id": 407669, "client": True, "template": 48827,
            "skill_line": SKILL_PROTECTION,
            "name": "Avenger's Shield", "inherit_server": True,
            "scale_to_level": {"effects": [1], "level": 80},
            "bonus": {"direct": 0.07, "dot": 0.0, "ap": 0.07, "ap_dot": 0.0},
            "overrides": {
                "CategoryRecoveryTime": 0,
                "DurationIndex": duration_5000,
                "RecoveryTime": 15000,
                "SpellLevel": 0,
            },
        },
        {  # Aura Mastery: the core script supplies the silence immunity.
            "id": 407624, "client": True, "template": 31821,
            "skill_line": SKILL_HOLY,
            "name": "Aura Mastery", "script": "spell_pal_aura_mastery",
            "inherit_server": True,
            "overrides": {
                "SpellLevel": 0,
            },
        },
        {  # Crusader Strike: retain its WotLK effect data and mana cost.
            "id": 407676, "client": True, "template": 35395,
            "skill_line": SKILL_RETRIBUTION,
            "name": "Crusader Strike", "inherit_server": True,
            "overrides": {
                "CategoryRecoveryTime": 0,
                "RecoveryTime": 6000,
                "SpellLevel": 0,
            },
        },
        {  # The Art of War: a melee critical reduces Exorcism's cooldown.
            "id": 426157, "client": True, "template": 53488,
            "inherit_server": True,
            "skill_line": SKILL_RETRIBUTION,
            "name": "The Art of War", "script": "spell_sod_paladin_art_of_war",
            "desc": "Your melee critical strikes reduce the remaining cooldown on Exorcism by $s2 sec, and the mana cost of Exorcism is reduced by $s1%.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "SpellClassSet": 10,
                "SpellIconID": icon_art_of_war,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "ProcTypeMask": 20, "ProcChance": 100, "ProcCharges": 0,
                # Aura 108 is ADD_PCT_MODIFIER; SpellModOp 14 is COST.
                # Exorcism uses WotLK SpellClassMask_2 bit 2.
                "Effect_1": EFFECT_APPLY_AURA, "EffectAura_1": 108,
                "EffectBasePoints_1": -80, "EffectDieSides_1": 0,
                "EffectAuraPeriod_1": 0,
                "EffectMiscValue_1": 14,
                "EffectMiscValueB_1": 0,
                "EffectTriggerSpell_1": 0,
                "EffectSpellClassMaskA_1": 0,
                "EffectSpellClassMaskB_1": 2,
                "EffectSpellClassMaskC_1": 0,
                "ImplicitTargetA_1": TARGET_UNIT_CASTER,
                "ImplicitTargetB_1": 0,
                "EffectRadiusIndex_1": 0,
                "Effect_2": EFFECT_APPLY_AURA, "EffectAura_2": AURA_DUMMY,
                "EffectBasePoints_2": 2, "EffectDieSides_2": 0,
                "EffectAuraPeriod_2": 0,
                "EffectMiscValue_2": 0, "EffectMiscValueB_2": 0,
                "EffectTriggerSpell_2": 0,
                "EffectSpellClassMaskA_2": 0,
                "EffectSpellClassMaskB_2": 0,
                "EffectSpellClassMaskC_2": 0,
                "ImplicitTargetA_2": TARGET_UNIT_CASTER,
                "ImplicitTargetB_2": 0,
                "EffectRadiusIndex_2": 0,
                "Effect_3": 0, "EffectAura_3": 0,
                "EffectBasePoints_3": 0, "EffectDieSides_3": 0,
                "ImplicitTargetA_3": 0,
            },
            "proc": {
                "SchoolMask": 0, "SpellFamilyName": 0,
                "SpellFamilyMask0": 0, "SpellFamilyMask1": 0,
                "SpellFamilyMask2": 0,
                # WotLK PROC_FLAG_DONE_MELEE_AUTO_ATTACK | DONE_SPELL_MELEE_DMG_CLASS.
                "ProcFlags": 20, "SpellTypeMask": 1,
                "SpellPhaseMask": 2, "HitMask": 2,
                "AttributesMask": 0, "DisableEffectsMask": 0,
                "ProcsPerMinute": 0, "Chance": 100,
                "Cooldown": 0, "Charges": 0,
            },
        },
        {  # Righteous Vengeance: reuse WotLK's 61840 accumulating periodic damage.
            "id": 440672, "client": True, "template": 53380,
            "inherit_server": True,
            "skill_line": SKILL_RETRIBUTION,
            "name": "Righteous Vengeance",
            "script": "spell_sod_paladin_righteous_vengeance",
            "desc": "When your Judgement, Crusader Strike, or Divine Storm deals a critical strike, your target will take $s1% additional damage over $61840d.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "EffectBasePoints_1": 30, "EffectDieSides_1": 0,
                "EffectBasePoints_2": 0, "EffectDieSides_2": 0,
                "EffectBasePoints_3": 0, "EffectDieSides_3": 0,
                "SpellIconID": icon_righteous_vengeance,
                "SpellLevel": 0, "EquippedItemClass": -1,
            },
            "proc": {
                "SchoolMask": 0, "SpellFamilyName": 10,
                # WotLK paladin Judgement, Crusader Strike, and Divine Storm masks.
                "SpellFamilyMask0": 0x00800000,
                "SpellFamilyMask1": 0x00028000,
                "SpellFamilyMask2": 0,
                "ProcFlags": 0, "SpellTypeMask": 1,
                "SpellPhaseMask": 2, "HitMask": 2,
                "AttributesMask": 0, "DisableEffectsMask": 0,
                "ProcsPerMinute": 0, "Chance": 0,
                "Cooldown": 0, "Charges": 0,
            },
        },
        {  # Improved Hammer of Wrath: instant cast plus a low-health cooldown reset.
            "id": 429152, "client": True, "template": 53488,
            "inherit_server": True,
            "name": "Improved Hammer of Wrath",
            "script": "spell_sod_paladin_improved_hammer_of_wrath",
            "desc": "Hammer of Wrath is now instant and the cooldown on Hammer of Wrath is reset each time it damages an enemy below $s1% health.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_permanent,
                "RangeIndex": range_self, "PowerType": 0, "ManaCost": 0,
                "ManaCostPct": 0, "SchoolMask": 2,
                "SpellClassSet": 10, "SpellClassMask_1": 0,
                "SpellClassMask_2": 128, "SpellClassMask_3": 0,
                "SpellIconID": icon_hammer_of_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "ProcTypeMask": PROC_DONE_MAGIC_NEG, "ProcChance": 100,
                # Effect 0 carries the tooltip threshold; effect 1 removes cast time.
                "Effect_1": EFFECT_APPLY_AURA, "EffectAura_1": AURA_DUMMY,
                "EffectBasePoints_1": 10, "EffectDieSides_1": 0,
                "ImplicitTargetA_1": TARGET_UNIT_CASTER,
                "EffectSpellClassMaskA_1": 0,
                "EffectSpellClassMaskB_1": 128,
                "EffectSpellClassMaskC_1": 0,
                "Effect_2": EFFECT_APPLY_AURA, "EffectAura_2": AURA_ADD_PCT_MODIFIER,
                "EffectBasePoints_2": -100, "EffectDieSides_2": 0,
                "EffectMiscValue_2": 10,  # SPELLMOD_CASTING_TIME in this core.
                "ImplicitTargetA_2": TARGET_UNIT_CASTER,
                "EffectSpellClassMaskA_2": 0,
                "EffectSpellClassMaskB_2": 128,
                "EffectSpellClassMaskC_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
            "proc": {
                "SchoolMask": 0, "SpellFamilyName": 10,
                "SpellFamilyMask0": 0, "SpellFamilyMask1": 128,
                "SpellFamilyMask2": 0,
                "ProcFlags": PROC_DONE_MAGIC_NEG, "SpellTypeMask": 1,
                "SpellPhaseMask": 2, "HitMask": 0,
                "AttributesMask": 0, "DisableEffectsMask": 2,
                "ProcsPerMinute": 0, "Chance": 100,
                "Cooldown": 0, "Charges": 0,
            },
        },
        {  # Purifying Power shortens cooldowns and grants the SoD Holy Wrath rank.
            "id": 429144, "client": True, "template": 20215,
            "inherit_server": True,
            "name": "Purifying Power",
            "script": "spell_sod_paladin_purifying_power",
            "desc": "Reduces the cooldown on Exorcism and Holy Wrath by $s1%, and Holy Wrath can now be cast at any target and will Stun Undead and Demon targets for $429147d.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_permanent,
                "RangeIndex": range_self, "PowerType": 0, "ManaCost": 0,
                "ManaCostPct": 0, "SchoolMask": 2,
                "SpellClassSet": 10, "SpellClassMask_1": 0,
                "SpellClassMask_2": 0, "SpellClassMask_3": 0,
                "SpellIconID": icon_holy_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "Effect_1": EFFECT_APPLY_AURA,
                "EffectAura_1": AURA_ADD_PCT_MODIFIER,
                "EffectBasePoints_1": -50, "EffectDieSides_1": 0,
                "EffectMiscValue_1": 11,  # SPELLMOD_COOLDOWN in this core.
                "ImplicitTargetA_1": TARGET_UNIT_CASTER,
                # WotLK masks: Exorcism (word 1 bit 1), Holy Wrath (word 1 bit 21).
                "EffectSpellClassMaskA_1": 0,
                "EffectSpellClassMaskB_1": 2097154,
                "EffectSpellClassMaskC_1": 0,
                "Effect_2": EFFECT_APPLY_AURA, "EffectAura_2": AURA_DUMMY,
                "EffectBasePoints_2": 0, "EffectDieSides_2": 0,
                "ImplicitTargetA_2": TARGET_UNIT_CASTER,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
        },
        {  # Fanaticism adds Holy spell critical chance and a four-tick critical-heal HoT.
            "id": 429142, "client": True, "template": 20215,
            "inherit_server": True,
            "name": "Fanaticism",
            "script": "spell_sod_paladin_fanaticism",
            "desc": "Increases your critical strike chance with Holy spells by $s1%. In addition, your critical healing spells heal the target for $s2% of the healed amount over $426162d.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_permanent,
                "RangeIndex": range_self, "PowerType": 0, "ManaCost": 0,
                "ManaCostPct": 0, "SchoolMask": 2,
                "SpellClassSet": 10, "SpellClassMask_1": 0,
                "SpellClassMask_2": 0, "SpellClassMask_3": 0,
                "SpellIconID": icon_fanaticism,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "ProcTypeMask": PROC_DONE_MAGIC_POS | PROC_DONE_PERIODIC,
                "ProcChance": 100,
                "Effect_1": EFFECT_APPLY_AURA,
                "EffectAura_1": AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL,
                "EffectBasePoints_1": 18, "EffectDieSides_1": 0,
                "EffectMiscValue_1": 2,  # SPELL_SCHOOL_MASK_HOLY.
                "ImplicitTargetA_1": TARGET_UNIT_CASTER,
                "Effect_2": EFFECT_APPLY_AURA, "EffectAura_2": AURA_DUMMY,
                "EffectBasePoints_2": 60, "EffectDieSides_2": 0,
                "ImplicitTargetA_2": TARGET_UNIT_CASTER,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
            "proc": {
                "SchoolMask": 0, "SpellFamilyName": 0,
                "SpellFamilyMask0": 0, "SpellFamilyMask1": 0,
                "SpellFamilyMask2": 0,
                "ProcFlags": PROC_DONE_MAGIC_POS | PROC_DONE_PERIODIC,
                "SpellTypeMask": 2, "SpellPhaseMask": 2,
                "HitMask": PROC_HIT_CRITICAL,
                "AttributesMask": 2, "DisableEffectsMask": 0,
                "ProcsPerMinute": 0, "Chance": 100,
                "Cooldown": 0, "Charges": 0,
            },
        },
        {  # 426162: server-cast HoT; its four ticks total 60% of a critical heal.
            "id": 426162, "client": True, "template": 774,
            "name": "Fanaticism", "aura_desc": "Heals $w1 every $t1 sec.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE | SPELL_ATTR0_DO_NOT_DISPLAY,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_12s,
                "RangeIndex": idx["range"][40.0], "PowerType": 0,
                "ManaCost": 0, "ManaCostPct": 0, "SchoolMask": 2,
                "SpellIconID": icon_fanaticism,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "Effect_1": EFFECT_APPLY_AURA, "EffectAura_1": AURA_PERIODIC_HEAL,
                "EffectAuraPeriod_1": 3000, "EffectBasePoints_1": 0,
                "ImplicitTargetA_1": TARGET_UNIT_TARGET_ALLY,
                "Effect_2": 0, "EffectAura_2": 0, "ImplicitTargetA_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
            "bonus": {"direct": 0.0, "dot": 0.0, "ap": 0.0, "ap_dot": 0.0},
        },
        {  # Wrath: dynamic melee crit chance for the listed Holy family spells.
            "id": 429139, "client": True, "template": 53375,
            "inherit_server": True,
            "name": "Wrath", "script": "spell_sod_paladin_wrath",
            "desc": "Your Consecration damage can now be critical strikes, and damage from your Exorcism, Holy Shock, Sunlight, Holy Wrath, and Consecration spells gains additional critical strike chance equal to your melee critical strike chance.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_permanent,
                "RangeIndex": range_self, "PowerType": 0, "ManaCost": 0,
                "ManaCostPct": 0, "SchoolMask": 2,
                "SpellClassSet": 10, "SpellClassMask_1": 0,
                "SpellClassMask_2": 0, "SpellClassMask_3": 0,
                "SpellIconID": icon_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "Effect_1": EFFECT_APPLY_AURA, "EffectAura_1": AURA_DUMMY,
                "EffectBasePoints_1": 0, "EffectDieSides_1": 0,
                "ImplicitTargetA_1": TARGET_UNIT_CASTER,
                "Effect_2": EFFECT_APPLY_AURA,
                "EffectAura_2": AURA_ABILITY_PERIODIC_CRIT,
                "EffectBasePoints_2": 0, "EffectDieSides_2": 0,
                "ImplicitTargetA_2": TARGET_UNIT_CASTER,
                # Consecration's WotLK SpellFamilyFlags word 0 is bit 5.
                "EffectSpellClassMaskA_2": 32,
                "EffectSpellClassMaskB_2": 0,
                "EffectSpellClassMaskC_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
        },
        {  # SoD rank 1: 2s Holy Wrath area damage, unrestricted creature types.
            "id": 429145, "client": True, "template": 2812,
            "inherit_server": True,
            "skill_line": SKILL_HOLY,
            "name": "Holy Wrath", "script": "spell_sod_paladin_purifying_power_holy_wrath",
            "desc": "Sends bolts of holy power in all directions, causing $s1 Holy damage to all targets within $a1 yds and Stunning Demon and Undead targets for $429147d.",
            "bonus": {"direct": 0.19, "dot": 0.0, "ap": 0.0, "ap_dot": 0.0},
            "overrides": {
                "Attributes": 0,
                "CastingTimeIndex": cast_2s, "DurationIndex": 0,
                "RangeIndex": range_self,
                "RecoveryTime": 0, "CategoryRecoveryTime": 60000,
                "StartRecoveryCategory": 133, "StartRecoveryTime": 1500,
                "SchoolMask": 2, "DefenseType": 1,
                "SpellIconID": icon_holy_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "TargetCreatureType": 0,
                "SpellClassSet": 10,
                "SpellClassMask_1": 0, "SpellClassMask_2": 2097152,
                "SpellClassMask_3": 0,
                "Effect_1": EFFECT_SCHOOL_DAMAGE, "EffectAura_1": 0,
                "EffectBasePoints_1": 361, "EffectDieSides_1": 67,
                "EffectRealPointsPerLevel_1": 1.6,
                "ImplicitTargetA_1": 22, "ImplicitTargetB_1": 15,
                "Effect_2": 0, "EffectAura_2": 0,
                "EffectBasePoints_2": 0, "ImplicitTargetA_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
        },
        {  # SoD rank 2: values and rank chosen from the Paladin's WotLK Holy Wrath rank.
            "id": 429146, "client": True, "template": 10318,
            "inherit_server": True,
            "skill_line": SKILL_HOLY,
            "name": "Holy Wrath", "script": "spell_sod_paladin_purifying_power_holy_wrath",
            "desc": "Sends bolts of holy power in all directions, causing $s1 Holy damage to all targets within $a1 yds and Stunning Demon and Undead targets for $429147d.",
            "bonus": {"direct": 0.19, "dot": 0.0, "ap": 0.0, "ap_dot": 0.0},
            "overrides": {
                "Attributes": 0,
                "CastingTimeIndex": cast_2s, "DurationIndex": 0,
                "RangeIndex": range_self,
                "RecoveryTime": 0, "CategoryRecoveryTime": 60000,
                "StartRecoveryCategory": 133, "StartRecoveryTime": 1500,
                "SchoolMask": 2, "DefenseType": 1,
                "SpellIconID": icon_holy_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "TargetCreatureType": 0,
                "SpellClassSet": 10,
                "SpellClassMask_1": 0, "SpellClassMask_2": 2097152,
                "SpellClassMask_3": 0,
                "Effect_1": EFFECT_SCHOOL_DAMAGE, "EffectAura_1": 0,
                "EffectBasePoints_1": 489, "EffectDieSides_1": 87,
                "EffectRealPointsPerLevel_1": 1.9,
                "ImplicitTargetA_1": 22, "ImplicitTargetB_1": 15,
                "Effect_2": 0, "EffectAura_2": 0,
                "EffectBasePoints_2": 0, "ImplicitTargetA_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
        },
        {  # Hidden two-second stun aura applied only to Demon and Undead targets.
            "id": 429147, "client": True, "template": 853,
            "inherit_server": True,
            "name": "Stun", "script": "spell_sod_paladin_purifying_power_stun",
            "aura_desc": "Stunned.",
            "overrides": {
                "Attributes": SPELL_ATTR0_PASSIVE | SPELL_ATTR0_DO_NOT_DISPLAY,
                "CastingTimeIndex": cast_instant, "DurationIndex": duration_2s,
                "RangeIndex": range_self,
                "RecoveryTime": 0, "CategoryRecoveryTime": 0,
                "StartRecoveryCategory": 0, "StartRecoveryTime": 0,
                "SchoolMask": 2, "SpellIconID": icon_holy_wrath,
                "SpellLevel": 0, "EquippedItemClass": -1,
                "Effect_1": EFFECT_APPLY_AURA, "EffectAura_1": AURA_MOD_STUN,
                "EffectBasePoints_1": -1, "EffectDieSides_1": 1,
                "EffectMechanic_1": 12,
                "ImplicitTargetA_1": TARGET_UNIT_TARGET_ENEMY,
                "Effect_2": 0, "EffectAura_2": 0, "ImplicitTargetA_2": 0,
                "Effect_3": 0, "EffectAura_3": 0, "ImplicitTargetA_3": 0,
            },
        },
    ]
